/**
 * v2/gateTaskTemplate.js — Gate 1-4 pilot task template.
 *
 * Source of truth for what template gets stamped onto a new bid:
 * docs/GATES_1_4_IMPLEMENTATION_PLAN.md §3 (Gate Criterion Mapping). Every
 * criterion from that document is here verbatim in `criterion_text`, plus a
 * `plain_text` one-liner for the PC-facing UI (the plan itself is written
 * for the audit trail, not for someone clicking through a checklist).
 *
 * This is a PILOT against a DRAFT SOP (LIS-OPS-001, reviewed 2026-08-11,
 * not yet effective) — see the plan's header. `SOP_VERSION` below is
 * intentionally an explicit draft identifier, never blank, so every task
 * instance can show which version of the (still-changing) SOP it was
 * stamped from.
 *
 * Do not edit criterion_text/gate/evidence_class/responsible_role on an
 * existing template entry to "fix" wording — that would silently change
 * what already-created task instances appear to have been stamped from.
 * Bump TEMPLATE_VERSION and add a new entry instead once this pilot needs
 * a real template revision (see plan §4.2.2).
 */

const SOP_DOCUMENT_NUMBER = 'LIS-OPS-001';
const SOP_VERSION = 'draft-reviewed-2026-08-11';
const TEMPLATE_VERSION = 'gate-1-4-pilot-v1';

const EVIDENCE_CLASS = {
  AUTOMATIC: 'automatic_evidence',
  MANUAL: 'manual_attestation',
  VERIFICATION: 'gate_verification',
};

// responsible_role is free text matching the plan's own wording (§3), not
// a TeamMember.role enum — the Calendar's current role model doesn't yet
// express PC/Lead Estimator/Superintendent/etc. as distinct roles (plan
// §5 and §9 item 5). Routing/permissions by role is a pilot open item,
// not assumed here.
const GATE_TASK_TEMPLATE = [
  // ── Gate 1 — Business Development and Lead Generation ──────────────────
  { task_key: 'g1.scope_alignment', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Scope aligns with LIS trade capabilities',
    plain_text: 'Confirm this is work LIS actually does.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g1.union_labor_available', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Union labor confirmed available in jurisdiction',
    plain_text: 'Confirm the union hall has labor available where this job is.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Superintendent / Operations Manager' },
  { task_key: 'g1.estimating_bandwidth', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Estimating bandwidth confirmed against calendar',
    plain_text: 'Confirm the estimating team has time to bid this.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g1.backlog_capacity', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Backlog and field capacity available',
    plain_text: 'Confirm the field has room to take this on if we win it.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Operations Manager / Superintendent' },
  { task_key: 'g1.margin_threshold', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Margin potential meets threshold',
    plain_text: 'Confirm the expected margin is worth bidding.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g1.gc_relationship', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'GC/owner relationship and payment history acceptable',
    plain_text: 'Confirm this GC/owner pays reliably and we want to work with them.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Business Development' },
  { task_key: 'g1.decision_recorded', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Decision and reason recorded on Estimating Calendar',
    plain_text: 'Approve-to-bid decision recorded in the Calendar.',
    evidence_class: EVIDENCE_CLASS.AUTOMATIC, responsible_role: 'PC' },
  { task_key: 'g1.out_of_scope', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Out of scope or trade coverage gap',
    plain_text: 'If passing: record why it is outside our trade scope.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g1.union_unavailable', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Union labor unavailable in local',
    plain_text: 'If passing: record that union labor was not available.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Superintendent / Operations Manager' },
  { task_key: 'g1.backlog_at_capacity', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Backlog at capacity',
    plain_text: 'If passing: record that we are at capacity.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Operations Manager / Superintendent' },
  { task_key: 'g1.travel_ot_pla_risk', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Excessive travel, OT, or PLA exposure',
    plain_text: 'If passing: record travel / overtime / PLA risk.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g1.margin_risk_unacceptable', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Margin or risk unacceptable',
    plain_text: 'If passing: record that margin/risk does not work.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g1.poor_payment_history', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Poor GC/owner payment history',
    plain_text: 'If passing: record payment-history concerns.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Business Development' },
  { task_key: 'g1.decline_gc_notified', gate: 1, phase: 'Business Development and Lead Generation',
    criterion_text: 'Decline recorded and GC notified — archive opportunity',
    plain_text: 'If passing: confirm the GC was told and the opportunity is archived.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },

  // ── Gate 2 — Bid Preparation and Setup ──────────────────────────────────
  { task_key: 'g2.project_hq_created', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Bid created in Project HQ with correct numbering',
    plain_text: 'Confirm the bid exists in Project HQ with the right number.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.onedrive_folder', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'OneDrive folder populated and complete',
    plain_text: 'Confirm the OneDrive folder is set up and has what it needs.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.accubid_job', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Accubid job created and linked to A: Drive',
    plain_text: 'Confirm the Accubid job exists and is linked correctly.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.plans_specs_addenda', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'All plans, specs, and addenda downloaded and broken out by trade',
    plain_text: 'Confirm plans/specs/addenda are downloaded and sorted by trade.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.jis_started', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'JIS started and linked',
    plain_text: 'Confirm the Job Information Sheet is started and linked.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.calendar_updated_no_conflicts', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Estimating Calendar updated with no conflicts',
    plain_text: 'Bid set up in the Calendar with no scheduling conflicts.',
    evidence_class: EVIDENCE_CLASS.AUTOMATIC, responsible_role: 'PC' },
  { task_key: 'g2.prequalification_current', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Prequalification and compliance documents current',
    plain_text: 'Confirm prequalification/compliance paperwork is current.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC / Executive Assistant' },
  { task_key: 'g2.action_item_estimator', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Action item issued to estimator',
    plain_text: 'Confirm the estimator has a Project HQ action item.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.incomplete_docs_hold', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Incomplete document set from GC — request missing items before release',
    plain_text: 'If docs are incomplete: record the request for missing items.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.prequal_not_current', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Prequalification not current — cannot submit',
    plain_text: 'If prequalification lapsed: record the hold.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g2.bandwidth_conflict_escalate', gate: 2, phase: 'Bid Preparation and Setup',
    criterion_text: 'Estimating bandwidth conflict identified — escalate to Lead Estimator',
    plain_text: 'If there is a bandwidth conflict: record the escalation.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC / Lead Estimator' },

  // ── Gate 3 — Estimate Takeoff and Submission ────────────────────────────
  { task_key: 'g3.takeoff_complete', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Takeoff complete and all addenda incorporated',
    plain_text: 'Confirm takeoff is done and every addendum is included.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Estimator' },
  { task_key: 'g3.labor_rates_verified', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Labor rates, burden, and wage determination verified',
    plain_text: 'Confirm labor rates/burden/wage determination were checked.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g3.sub_quotes_leveled', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Sub quotes leveled and compliant subs selected',
    plain_text: 'Confirm sub quotes are leveled and the subs are compliant.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Estimator / PC' },
  { task_key: 'g3.internal_review', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Internal review complete and markup applied',
    plain_text: 'Confirm the internal review happened and markup was applied.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g3.executive_signoff', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Executive sign-off obtained where required',
    plain_text: 'Confirm executive sign-off, if this bid needs it.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Executive' },
  { task_key: 'g3.submitted_before_deadline', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Proposal submitted before deadline with written receipt confirmation',
    plain_text: 'Confirm it was submitted on time with a written receipt.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Estimator / PC' },
  { task_key: 'g3.submission_logged', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Submission logged in Project HQ and Estimating Calendar',
    plain_text: 'Confirm it is logged in Project HQ (Calendar side is automatic).',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g3.scope_ambiguity_qualified', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Scope ambiguity unresolved at bid deadline — qualify the exclusion in writing',
    plain_text: 'If scope was unclear at deadline: record the written qualification.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Estimator' },
  { task_key: 'g3.sub_coverage_escalate', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Insufficient sub coverage on a required scope — escalate to Lead Estimator',
    plain_text: 'If sub coverage was short: record the escalation.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Estimator' },
  { task_key: 'g3.wage_determination_unavailable', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Wage determination unavailable — do not submit without qualification',
    plain_text: 'If wage determination was missing: record the qualification.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
  { task_key: 'g3.executive_signoff_missing', gate: 3, phase: 'Estimate Takeoff and Submission',
    criterion_text: 'Executive sign-off not obtained on a threshold bid',
    plain_text: 'If required sign-off was missing: record the hold/exception.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC / Lead Estimator' },

  // ── Gate 4 — Sales Follow-Up and Award Decision ─────────────────────────
  { task_key: 'g4.pilot_verification', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Gate 4 verified by Operations Manager — PC recused',
    plain_text: 'Gate 4 verification — PC verifies during this pilot.',
    evidence_class: EVIDENCE_CLASS.VERIFICATION, responsible_role: 'PC (pilot exception — SOP draft assigns this to Operations Manager)',
    pilot_exception: 'The current draft SOP assigns Gate 4 verification to the Operations Manager, with the PC recused. For this pilot, the PC verifies Gate 4 instead — a documented, time-bounded exception (plan §Pilot Decisions, §5). This is not a change to the published SOP.' },
  { task_key: 'g4.written_award_notice', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Written award notification received',
    plain_text: 'Confirm we received the award in writing.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Business Development / PC' },
  { task_key: 'g4.award_value_matches', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Award value and scope match submitted proposal or a re-priced revision',
    plain_text: 'Confirm the award amount/scope matches what we proposed.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g4.estimate_package_complete', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Estimate package and job folder confirmed complete',
    plain_text: 'Confirm the estimate package and job folder are complete.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Estimator / PC' },
  { task_key: 'g4.all_systems_awarded', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'All systems updated to Awarded',
    plain_text: 'Confirm every system (not just the Calendar) shows Awarded.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g4.verbal_award_only', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Award communicated verbally only — obtain in writing before proceeding',
    plain_text: 'If award was only verbal: record the hold until written.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g4.award_value_mismatch', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Award value does not match the proposal — reconcile before acceptance',
    plain_text: 'If the award amount is off: record the reconciliation.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'PC' },
  { task_key: 'g4.scope_reduced_repricing', gate: 4, phase: 'Sales Follow-Up and Award Decision',
    criterion_text: 'Scope reduced without re-pricing — return to Lead Estimator',
    plain_text: 'If scope was cut without re-pricing: record the return to Lead Estimator.',
    evidence_class: EVIDENCE_CLASS.MANUAL, responsible_role: 'Lead Estimator' },
];

module.exports = { GATE_TASK_TEMPLATE, SOP_DOCUMENT_NUMBER, SOP_VERSION, TEMPLATE_VERSION, EVIDENCE_CLASS };
